### ISSUE TITLE
file etnlp_api.py?

### ISSUE THREAD

**Issue by phuongdt96** [vietnlp/etnlp#1]
Em chào anh.
Em muốn hỏi file etnlp_api.py trong video demo mình tạo ra hay lấy ở đâu ạ?

**Comment by sonvx** [comment]
A sẽ release code sớm em nhé. E định dùng cho bài toán nào hay cũng để thử kết hợp các embedding?

**Comment by phuongdt96** [comment]
Dạ. Em làm môn tiểu luận khoa học về Nhận dạng thực thể có tên (NER) ạ, em
đang tìm hiểu mô hình NER, em muốn chạy thử để lấy word embedding để chạy
lại VnCoreNLP. Em chạy thử ETNLP của anh theo video demo chỗ etnlp_api.py
em không biết.

Vào Th 7, 30 thg 3, 2019 vào lúc 21:28 sonvx <notifications@github.com>
đã viết:

**Comment by sonvx** [comment]
ừ, các embedding cho NER task đã đc a đưa lên đầy đủ, em thử trc với vncorenlp để xem performance thế nào nhé. Có gì em nhắn lại đây để a đc biết 👍 .

**Comment by phuongdt96** [comment]
em muốn chạy lại cái video demo của anh để lấy các file output nữa ạ, nhưng
em bị vướng chỗ file etnlp_api.py em không biết nó viết như nào?

Vào Th 2, 1 thg 4, 2019 vào lúc 15:19 sonvx <notifications@github.com> đã
viết:

**Comment by sonvx** [comment]
Pipeline: embeddings -> ETNLP -> embeddings_for_NER -> vncoreNLP -> evaluation results. 
các embeddings_for_NER đã đc đưa lên nên **em chưa cần** chạy lại ETNLP để test với vncorenlp  em nhé. etnlp_api.py là hàm api đến các features của ETNLP và sẽ đc release cùng package em nhé.

**Comment by phuongdt96** [comment]
Anh có thể hướng dẫn em cách áp dụng mấy cái nhúng đào tạo trước vào vncorenlp k ạ?

**Comment by sonvx** [comment]
Code available rồi em nhé. Em xem README.md để xem cách dùng nhé.
